---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  tags: apache,apache2,ubuntu
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  tags: ubuntu,db,mariadb
  become: true
  tasks:
  
  - name: install mariadb package (Ubuntu)
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  tags: samba
  become: true
  tasks:
 
  - name: install samba package
    package:
      name: samba
      state: latest
