 - name: install apache2 package (Ubuntu)
   tags: apache,php,ubuntu
   package:
     name:
       - "{{ apache_package_name }}"
       - "{{ php_package_name }}"
     state: latest

 - name: copy default html file for site
   tags: apache,apache2
   copy:
     src: "default_site.html"
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644 
